config/routes.rb
Rails.application.routes.draw do

  resources :tips
  devise_for :users
  get 'welcome/index'

  root 'tips#index'

end

app/models/tip.rb
class Tip < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!
  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end

  # GET /tips/new
  def new
    @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)

    respond_to do |format|
      if @tip.save
        format.html { redirect_to @tip, notice: 'Tip was successfully created.' }
        format.json { render :show, status: :created, location: @tip }
      else
        format.html { render :new }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to tips_url, notice: 'Tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:start_date, :end_date, :monday_amount, :tuesday_amount, :wednesday_amount, :thursday_amount, :friday_amount, :saturday_amount, :sunday_amount, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
	    :user
	end

	def resource
	    @resource ||= User.new
	end

	def devise_mapping
	    @devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/tips_helper.rb
module TipsHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TipTally</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


  <!--JQuer-->
  <script   src="https://code.jquery.com/jquery-2.2.3.js"   integrity="sha256-laXWtGydpwqJ8JA+X9x2miwmaiKhn8tVmOVEigRNtP4="   crossorigin="anonymous"></script>
	
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
	<!-- JavaScript needed for google chart -->
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

</head>

<body>
	<!-- Nav bar -->
	<div class="container">
	  <nav class="navbar navbar-default">
	    <div class="container-fluid">
	      <!-- Brand and toggle get grouped for better mobile display -->
	      <div class="navbar-header">
	        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	          <span class="sr-only">Toggle navigation</span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </button>
	        <%= link_to image_tag('tip-logo-2.png'), tips_path, class:"navbar-brand" %> 
	      </div>

	      <!-- Collect the nav links, forms, and other content for toggling -->
	      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	        <ul class="nav navbar-nav">
	          <li class="active"><%= link_to "Profile", edit_user_registration_path %> </li>
	          <li class="active"><%= link_to "Log Out", destroy_user_session_path, method: :delete %> </li>
	        </ul>
	      </div><!-- /.navbar-collapse -->
	    </div><!-- /.container-fluid -->
	  </nav>
	</div>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>

</body>

</html>

app/views/tips/_form.html.erb
 <%= form_for(@tip) do |f| %>
  <% if @tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>



      <ul>
      <% @tip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field" hidden>
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :monday_amount %><br>
    <%= f.text_field :monday_amount %>
  </div>
  <div class="field">
    <%= f.label :tuesday_amount %><br>
    <%= f.text_field :tuesday_amount %>
  </div>
  <div class="field">
    <%= f.label :wednesday_amount %><br>
    <%= f.text_field :wednesday_amount %>
  </div>
  <div class="field">
    <%= f.label :thursday_amount %><br>
    <%= f.text_field :thursday_amount %>
  </div>
  <div class="field">
    <%= f.label :friday_amount %><br>
    <%= f.text_field :friday_amount %>
  </div>
  <div class="field">
    <%= f.label :saturday_amount %><br>
    <%= f.text_field :saturday_amount %>
  </div>
  <div class="field">
    <%= f.label :sunday_amount %><br>
    <%= f.text_field :sunday_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  

<% end %>
</div>

app/views/tips/edit.html.erb
<h1>Editing Tip</h1>

<%= render 'form' %>

<%= link_to 'Show', @tip %> |
<%= link_to 'Back', tips_path %>

app/views/tips/hybrid.html.erb
<!-- adding graph-->
<div class="row">
  <div class= "col-md-2"></div>
  <figure class="chart">
    <canvas id="chart-0" width=1000 height=500></canvas>
    <!-- legend rendered here -->
  </figure>
  <script type="text/javascript">
    (function() {
      var initChart = function() {
        var data = 
        {
            labels: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
            datasets: [
                {
                    label: "My First dataset",
                    fillColor: "rgba(220,220,220,0.2)",
                    strokeColor: "rgba(220,220,220,1)",
                    pointColor: "rgba(220,220,220,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(220,220,220,1)",
                    data: [ <%= @tips[0].monday_amount %>, <%= @tips[0].tuesday_amount %>, <%= @tips[0].wednesday_amount %>, <%= @tips[0].thursday_amount %>, <%= @tips[0].friday_amount %>, <%= @tips[0].saturday_amount %>, <%= @tips[0].sunday_amount %>]
                },
            ]
        }
        var opts = {"scaleFontSize":15};
        if (!("animation" in opts)) {
          opts['animation'] = (typeof Modernizr == "undefined") || Modernizr.canvas;
        }
        var canvas = document.getElementById("chart-0");
        var ctx = canvas.getContext('2d');
        var chart = new Chart(ctx).Bar(data, opts);
        window.Chart["chart-0"] = chart;

        //creating graph without legend
        //var legend = chart.generateLegend();
        //var legendHolder = document.createElement("div");
        //legendHolder.innerHTML = legend;
        //canvas.parentNode.insertBefore(legendHolder.firstChild, canvas.nextSibling);
      };
      if (typeof Chart !== "undefined" && Chart !== null) {
        initChart();
      }
      else {
        if (window.addEventListener) {
          window.addEventListener("load", initChart, false);
        }
        else if (window.attachEvent) {
          window.attachEvent("onload", initChart);
        }
      }
    })();
  </script>
</div>

app/views/tips/index.html.erb
<!-- adding graph-->
<div class="row">
  <div class="col-md-8">
  </div>
  <div class = "total" id = "header total">
    <p> Total <%= @tips[-1].monday_amount + @tips[-1].tuesday_amount + @tips[-1].wednesday_amount + @tips[-1].thursday_amount + @tips[-1].friday_amount + @tips[-1].saturday_amount + @tips[-1].sunday_amount %> </p>
  </div>
</div>
<div class="row">
  <div class= "col-md-2"></div>
  <figure class="chart">
    <canvas id="chart-0" width=1000 height=500></canvas>
    <!-- legend rendered here -->
  </figure>
  <script type="text/javascript">
    (function() {
      var initChart = function() {
        var data = 
        {
            labels: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
            datasets: [
                {
                    label: "Current week's tips",
                    fillColor: "rgba(220,220,220,0.2)",
                    strokeColor: "rgba(220,220,220,1)",
                    pointColor: "rgba(220,220,220,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(220,220,220,1)",
                    data: [ <%= @tips[-1].monday_amount %>, <%= @tips[-1].tuesday_amount %>, <%= @tips[-1].wednesday_amount %>, <%= @tips[-1].thursday_amount %>, <%= @tips[-1].friday_amount %>, <%= @tips[-1].saturday_amount %>, 
                    <%= @tips[-1].sunday_amount %>]
                },
            ]
        }
        var opts = {"scaleFontSize":15, "scaleShowGridLines":false};
        if (!("animation" in opts)) {
          opts['animation'] = (typeof Modernizr == "undefined") || Modernizr.canvas;
        }
        var canvas = document.getElementById("chart-0");
        var ctx = canvas.getContext('2d');
        var chart = new Chart(ctx).Bar(data, opts);
        window.Chart["chart-0"] = chart;

        // creating graph without legend
        // var legend = chart.generateLegend();
        // var legendHolder = document.createElement("div");
        // legendHolder.innerHTML = legend;
        // canvas.parentNode.insertBefore(legendHolder.firstChild, canvas.nextSibling);
      };
      if (typeof Chart !== "undefined" && Chart !== null) {
        initChart();
      }
      else {
        if (window.addEventListener) {
          window.addEventListener("load", initChart, false);
        }
        else if (window.attachEvent) {
          window.attachEvent("onload", initChart);
        }
      }
    })();
  </script>
</div>

 

<% @tips.order('created_at ASC').reverse.each do |tip| %>
  <% next if tip == @tips[-1] %>
  <div id="chart_div"></div>
  <script>
    google.charts.load("current", {packages:["corechart"]});
    google.charts.setOnLoadCallback(drawChart);
    function drawChart(){
         var data = google.visualization.arrayToDataTable([
           ['Day', 'Total', { role: 'style' }, { role: 'annotation' } ],
           ['Monday', <%= tip.monday_amount %>, 'color: #e5e4e2', 'M' ],
           ['Tuesday', <%= tip.tuesday_amount %>, 'color: #e5e4e2', 'T' ],
           ['Wednesday', <%= tip.wednesday_amount %>, 'color: #e5e4e2', 'W' ],
           ['Thursday', <%= tip.thursday_amount %>, 'color: #e5e4e2', 'R' ],
           ['Friday', <%= tip.friday_amount %>, 'color: #e5e4e2', 'F' ],
           ['Saturday', <%= tip.saturday_amount %>, 'color: #e5e4e2', 'Sat' ],
           ['Sunday', <%= tip.sunday_amount %>, 'color: #e5e4e2', 'Sun' ]
        ]);

          var options = {
            chartArea: {width: '50%'},
            hAxis: {
              title: 'Total Tips Week of:',
              minValue: 0
            },
          };

          var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
          chart.draw(data, options);
        }
  </script> 
<%end%>

<% @tips.order('created_at ASC').reverse.each do |tip| %>
  <% next if tip == @tips[-1] %>
  <div class = "row">
    <div class = "col-md-6">
    </div>
    <div class= "col-md-3">
      <p> Week of: <%= tip.start_date%>  <%=tip.end_date %></p>
    </div>
    <div class = "col-md-3" class = "total">
      <p> Total: <%= tip.monday_amount + tip.tuesday_amount + tip.wednesday_amount + tip.thursday_amount + tip.friday_amount + tip.saturday_amount + tip.sunday_amount  %></p>
    </div>
  </div>
  <div class = "row">
    <div class="col-md-1">
      <%= tip.start_date %>
    </div>
    <div class="col-md-1">
      <%= tip.end_date %>
    </div>       
    <div class="col-md-1">
      <%= tip.monday_amount %>
    </div>
    <div class="col-md-1">
      <%= tip.tuesday_amount %>
    </div>
    <div class="col-md-1">
      <%= tip.wednesday_amount %>
    </div>
    <div class="col-md-1">
      <%= tip.thursday_amount %>
    </div>
    <div class="col-md-1">
      <%= tip.friday_amount %>
    </div>
    <div class="col-md-1">
      <%= tip.saturday_amount %>
    </div>
    <div class="col-md-1">
      <%= tip.sunday_amount %>
    </div>
    <div class="col-md-2">
    </div> 
    <div class="col-md-1">
      <%= link_to("Show", tip)%>
      <%= link_to("Edit", edit_tip_path(tip))%>
      <%= link_to("Destroy", tip, method: :delete, data: { confirm: 'Are you sure?'})%>
    </div>
  </div>        
<% end %>

app/views/tips/new.html.erb
<!-- Button trigger modal --> 
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
 Add Tips
</button>
<div class="modal fade"  id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog" role="document">
   <div class="modal-content">
     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
         <span aria-hidden="true">&times;</span>
       </button>
       <h4 class="modal-title" id="myModalLabel">Today's Tips</h4>
     </div>
     <div class="modal-body">

<%= render 'form' %>

</div>
     <div class="modal-footer">
       <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
       <button type="button" class="btn btn-primary">Save changes</button>
     </div>
   </div>
 </div>
</div>
</div>


<%= link_to 'Back', tips_path %>

app/views/tips/show.html.erb
<!-- notice -->
<p id="notice"><%= notice %></p>

<!-- adding graph-->
<div class="row">
  <div class= "col-md-2"></div>
  <figure class="chart">
    <canvas id="chart-0" width=1000 height=500></canvas>
    <!-- legend rendered here -->
  </figure>
  <script type="text/javascript">
    (function() {
      var initChart = function() {
        var data = 
        {
            labels: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
            datasets: [
                {
                    label: "My First dataset",
                    fillColor: "rgba(220,220,220,0.2)",
                    strokeColor: "rgba(220,220,220,1)",
                    pointColor: "rgba(220,220,220,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(220,220,220,1)",
                    data: [ <%= @tip.monday_amount %>, <%= @tip.tuesday_amount %>, <%= @tip.wednesday_amount %>, <%= @tip.thursday_amount %>,
                    <%= @tip.friday_amount %>, <%= @tip.saturday_amount %>, <%= @tip.sunday_amount %>]
                },
            ]
        }
        var opts = {"scaleFontSize":15};
        if (!("animation" in opts)) {
          opts['animation'] = (typeof Modernizr == "undefined") || Modernizr.canvas;
        }
        var canvas = document.getElementById("chart-0");
        var ctx = canvas.getContext('2d');
        var chart = new Chart(ctx).Bar(data, opts);
        window.Chart["chart-0"] = chart;

        //creating graph without legend
        //var legend = chart.generateLegend();
        //var legendHolder = document.createElement("div");
        //legendHolder.innerHTML = legend;
        //canvas.parentNode.insertBefore(legendHolder.firstChild, canvas.nextSibling);
      };
      if (typeof Chart !== "undefined" && Chart !== null) {
        initChart();
      }
      else {
        if (window.addEventListener) {
          window.addEventListener("load", initChart, false);
        }
        else if (window.attachEvent) {
          window.attachEvent("onload", initChart);
        }
      }
    })();
  </script>
</div>



<!-- tips field-->
<p>
  <strong>Start date:</strong>
  <%= @tip.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @tip.end_date %>
</p>

<p>
  <strong>Monday amount:</strong>
  <%= @tip.monday_amount %>
</p>

<p>
  <strong>Tuesday amount:</strong>
  <%= @tip.tuesday_amount %>
</p>

<p>
  <strong>Wednesday amount:</strong>
  <%= @tip.wednesday_amount %>
</p>

<p>
  <strong>Thursday amount:</strong>
  <%= @tip.thursday_amount %>
</p>

<p>
  <strong>Friday amount:</strong>
  <%= @tip.friday_amount %>
</p>

<p>
  <strong>Saturday amount:</strong>
  <%= @tip.saturday_amount %>
</p>

<p>
  <strong>Sunday amount:</strong>
  <%= @tip.sunday_amount %>
</p>

<%= link_to 'Edit', edit_tip_path(@tip) %> |
<%= link_to 'Back', tips_path %>

app/views/welcome/index.html.erb
<h1>Welcome Page</h1>
<p>Tip Tracker to come</p>

<% if user_signed_in? %>


<% else %>

<!-- Below is the form to place the sign-in fields on this page, no one is expecting you to memorize this code. Just remember where you can copying it from (like an old/this project, or in a special file of code you want easy access to). -->

<div class="container">
	<div class="col-md-6">
		<h3>Welcome Back! Sign In:</h3><br />
		<%= form_for(:user, :url => session_path(:user)) do |f| %>
		<p><strong>Email:</strong> <br>
		<%= f.text_field :email %></p>
		<p><strong>Password:</strong> <br>
		<%= f.password_field :password %></p>
		<p><%= f.check_box :remember_me %> <%= f.label :remember_me %></p>
		<p><%= f.submit 'Sign In' %></p>
		<p><%= link_to "Forgot your password?", new_password_path(:user) %></p>
	<% end %>
	</div>

	<div class="col-md-6">
		<h3>Not yet registered?</h3><br />

		<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
		<%= devise_error_messages! %>

		<p><%= f.label :name %><br />
		<%= f.text_field :name %></p>

		<p><%= f.label :email %><br />
		<%= f.email_field :email, autofocus: true %></p>

		<p><%= f.label :password %><br />
		<%= f.password_field :password, autocomplete: "off" %></p>

		<p><%= f.label :password_confirmation %><br />

		<%= f.password_field :password_confirmation, autocomplete: "off" %></p>

		<div><%= f.submit "Sign up" %></div>
		<% end %>
	</div>
</div>
<% end %>